package:
  name: deepsmirud
  version: 0.0.0.0.25

build:
  skip: True # [py<35]

source:
  path: https://github.com/2003100127/deepsmirud.git

requirements:
  build:
    - python==3.7
  run:
    - biopython
    - click
    - numpy
    - pandas
    - pyfiglet
    - python==3.7

about:
  home: https://github.com/2003100127/deepsmirud
  license: MIT
  license_family: MIT
  license_file: 
  summary: "deepsmirud"
  doc_url:
  dev_url: